### PR TITLE
big/57: Fixed branch protection rule decision

### LINKED ISSUE #57: Unfeasable branch protection rules
Due to the fact that pushing directly to `master/main` is prohibited in our repositories, adding branch protection rules which require
the execution of `workflows/actions` on the following event:
```yaml
on:
  push:
    branches:
      - main
```
will render PR's unmergeable (without administrative intervention e.g. deleting the specific branch protection rules).
For example see [this PR](https://github.com/exasol/integration-test-docker-environment/pull/222).

image

## Impact
The project never will be `Github-Keeper` compliant.
1. If it is complaint: PR's can't get merged
2. If it is manually fixed by adjusting the protection rules: The project won't be complaint 

## Root cause
Github-Keeper does not seem to take triggers of `workflow/action`s into account correctly.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #57

### CODE REVIEW

File: cmd/branchProtection.go [hunk 1]
```diff
@@ -52,7 +52,7 @@ func (verifier BranchProtectionVerifier) CheckIfBranchProtectionIsApplied(fix bo
 	repo := verifier.getRepo()
 	branch := *repo.DefaultBranch
```
Comment (kaklakariada) [inline cmd/branchProtection.go]:
```suggestion
	defaultBranch := *repo.DefaultBranch
```
(also other occurrences)

File: cmd/workflowDefinitionParser.go [hunk 2]
```diff
@@ -147,36 +136,93 @@ func (parser WorkflowDefinitionParser) replaceSpecificParameterInJobName(jobName
...
+	TriggerOnPushToAnyBranch bool
+}
+
+func getTriggersOfWorkflowDefinition(parsedYaml *workflowDefinitionInt) (*TriggerDefinition, error) {
+	if triggersFromArray := tryReadingTriggersFromArray(parsedYaml.On); triggersFromArray != nil {
+		return triggersFromArray, nil
+	} else if triggersFromMap := tryReadingTriggersFromMap(parsedYaml.On); triggersFromMap != nil {
+		return triggersFromMap, nil
 	} else {
 		return nil, fmt.Errorf("the GitHub workflow '%v' has a unimplemented trigger definition style", parsedYaml.Name)
```
Comment (kaklakariada) [inline cmd/workflowDefinitionParser.go:163]:
```suggestion
		return nil, fmt.Errorf("the GitHub workflow '%v' uses an unsupported trigger definition style", parsedYaml.Name)
```

File: cmd/branchProtection.go [hunk 3]
```diff
@@ -232,34 +232,59 @@ func (verifier BranchProtectionVerifier) getRequiredChecks(requireSonar bool) ([
...
+	fmt.Printf("%vWarning: Failed to parse workflow definition '%v'. Probably you use some advanced matrix build features there. Github-keeper will not add the checks from this workflow to the branch protection. Please add them manually. %v\n", consoleColorYellow, fileUrl, consoleColorReset)
+}
+
+func checkIfProtectionNeeded(triggers *TriggerDefinition, defaultBranch string) bool {
+	if triggers.TriggerOnPr || triggers.TriggerOnPushToAnyBranch {
+		return true
+	}
+	for _, branch := range triggers.TriggerOnPushToBranches {
+		if branch == defaultBranch {
+			return true
```
Comment (tkilias) [inline cmd/branchProtection.go:284]: I think, this is an error, because this means the workflow is executed only on push. Or, is the intention here, if this workflow runs on the default branch it should also run on feature branch. I think, this is not correct, in all cases.

Comment (jakobbraun) [reply cmd/branchProtection.go:284]: that's true

**Review by kaklakariada — CHANGES_REQUESTED** [review]
