### PR TITLE
Bugfix #45 Fix workflow validation

### LINKED ISSUE #45: Validation of workflow files should ignore non-pr relevant files
github-keeper fails validation of workflow files even if these are not relevant for pull requests/branch protection:

`Validation Error for .github/workflows/release_droid_upload_github_release_assets.yml: matrix github-action jobs with object parameters and no job name are not supported. Please add a name field to the job that combines the matrix parameters into a more readable name. For example "Build with Go ${{matrix.go}} and Exasol ${{ matrix.db }}"`

github-keeper must ignore this kind of problem in non-relevant files.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #45

### CODE REVIEW

File: cmd/branchProtection.go [hunk 1]
```diff
@@ -226,28 +226,29 @@ func (verifier BranchProtectionVerifier) getChecksForWorkflow(workflowFilePath *
...
 	return emptyResult
 }
 
-func (verifier BranchProtectionVerifier) hasWorkflowPushOrPrTrigger(parsedYaml *workflowDefinition) bool {
-	for _, trigger := range parsedYaml.Trigger {
+func hasWorkflowPushOrPrTrigger(triggers []string) bool {
+	for _, trigger := range triggers {
 		if trigger == "push" || trigger == "pull_request" {
 			return true
 		}
```
Comment (jakobbraun) [inline cmd/branchProtection.go:254]: maybe move to dedicated file or "class"

File: cmd/workflowDefinitionParser.go [hunk 2]
```diff
@@ -30,7 +31,21 @@ func (parser WorkflowDefinitionParser) ParseWorkflowDefinition(content string) (
 		return nil, err
 	}
 	var jobNames []string
-	for jobKey, jobDescription := range parsedYaml.Jobs {
+	if hasWorkflowPushOrPrTrigger(trigger) {
```
Comment (jakobbraun) [inline cmd/workflowDefinitionParser.go:34]: maybe this method suites into this file.

**Review by jakobbraun — CHANGES_REQUESTED** [review]

**Review by jakobbraun — APPROVED** [review]
